apiVersion: v1
kind: Service
metadata:  
  name: es-nodeport
spec:
  selector:    
    service: elasticsearch
  type: NodePort
  ports:  
  - name: http
    port: 9200
    targetPort: 9200
    nodePort: 30036
    protocol: TCP